[package]
name = "shoppinglist"
version = "0.1.0"
authors = ["Nexuz <nexxuz0@googlemail.com>"]

[dependencies]
telegram-bot = { git = "https://github.com/Nexus87/telegram-bot" }
tokio = "0.1.13"
futures = "0.1.25"
todoist = { version = "=0.1.0", path = "../todoist" }
serde = "1.0.84"
serde_json = "1.0.35"
byteorder = "1.3.1"
sled = "0.23.0"
failure = "0.1.5"
log = "0.4.6"
simplelog = "0.5.3"
bincode = "1.1.3"
gotham = "0.4.0"
hyper = "0.12.33"
