[package]
name = "shoppinglist"
version = "0.1.0"
authors = ["Nexuz <nexxuz0@googlemail.com>"]
edition = "2018"

[dependencies]
telegram-bot = { git = "https://github.com/Nexus87/telegram-bot" }
tokio = "0.2.10"
futures = "0.3.1"
todoist = { version = "=0.1.0", path = "../todoist" }
serde = "1.0.104"
serde_json = "1.0.45"
byteorder = "1.3.2"
sled = "0.30.3"
failure = "0.1.6"
log = "0.4.8"
simplelog = "0.7.4"
bincode = "1.2.1"
gotham = "0.4.0"
hyper = "0.13.1"
